version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: build test image
          command: docker build --no-cache -t test-app -f docker/test.Dockerfile .

      - run:
          name: run tests
          command: docker run --rm test-app --name test-app
