version: '3.7'

services:
  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80  # should be 1337:80, but then reverse proxy for swagger.json needed
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    expose:
      - 5000